2025-04-03 19:02:50.654 T:7        info <general>: -----------------------------------------------------------------------
2025-04-03 19:02:50.654 T:7        info <general>: Starting Kodi (21.1 (21.1.0) Git:20240817-183eb85-dirty). Platform: Linux x86 64-bit
2025-04-03 19:02:50.654 T:7        info <general>: Using Release Kodi x64
2025-04-03 19:02:50.654 T:7        info <general>: Kodi compiled 2024-09-17 by GCC 13.2.0 for Linux x86 64-bit version 6.1.10 (393482)
2025-04-03 19:02:50.654 T:7        info <general>: Running on Freedesktop SDK 23.08 (Flatpak runtime), kernel: Linux x86 64-bit version 6.14.0-x64v3-xanmod1
2025-04-03 19:02:50.654 T:7        info <general>: FFmpeg version/source: 6.0.1
2025-04-03 19:02:50.654 T:7        info <general>: Host CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz, 4 cores available
2025-04-03 19:02:50.654 T:7        info <general>: special://xbmc/ is mapped to: /app/share/kodi
2025-04-03 19:02:50.654 T:7        info <general>: special://xbmcbin/ is mapped to: /app/lib/kodi
2025-04-03 19:02:50.654 T:7        info <general>: special://xbmcbinaddons/ is mapped to: /app/lib/kodi/addons
2025-04-03 19:02:50.654 T:7        info <general>: special://masterprofile/ is mapped to: /home/localhost/.var/app/tv.kodi.Kodi/data/userdata
2025-04-03 19:02:50.654 T:7        info <general>: special://envhome/ is mapped to: /home/localhost
2025-04-03 19:02:50.654 T:7        info <general>: special://home/ is mapped to: /home/localhost/.var/app/tv.kodi.Kodi/data
2025-04-03 19:02:50.654 T:7        info <general>: special://temp/ is mapped to: /home/localhost/.var/app/tv.kodi.Kodi/data/temp
2025-04-03 19:02:50.654 T:7        info <general>: special://logpath/ is mapped to: /home/localhost/.var/app/tv.kodi.Kodi/data/temp
2025-04-03 19:02:50.654 T:7        info <general>: Webserver extra whitelist paths: 
2025-04-03 19:02:50.654 T:7        info <general>: The executable running is: /app/lib/kodi/kodi.bin
2025-04-03 19:02:50.654 T:7        info <general>: Local hostname: localhost
2025-04-03 19:02:50.654 T:7        info <general>: Log File is located: /home/localhost/.var/app/tv.kodi.Kodi/data/temp/kodi.log
2025-04-03 19:02:50.654 T:7        info <general>: -----------------------------------------------------------------------
2025-04-03 19:02:50.654 T:7        info <general>: loading settings
2025-04-03 19:02:50.655 T:7        info <general>: special://profile/ is mapped to: special://masterprofile/
2025-04-03 19:02:50.660 T:7        info <general>: No settings file to load (special://xbmc/system/advancedsettings.xml)
2025-04-03 19:02:50.660 T:7        info <general>: No settings file to load (special://masterprofile/advancedsettings.xml)
2025-04-03 19:02:50.660 T:7        info <general>: Default Video Player: VideoPlayer
2025-04-03 19:02:50.660 T:7        info <general>: Default Audio Player: paplayer
2025-04-03 19:02:50.660 T:7        info <general>: Disabled debug logging due to GUI setting. Level 0.
2025-04-03 19:02:50.660 T:7        info <general>: Log level changed to "info"
2025-04-03 19:02:50.660 T:7        info <general>: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
2025-04-03 19:02:50.661 T:7        info <general>: New Cache GUI Settings (replacement of cache in advancedsettings.xml) are:
                                                     Buffer Mode: 4
                                                     Memory Size: 20 MB
                                                     Read Factor: 4.00 x 
                                                     Chunk Size : 131072 bytes
2025-04-03 19:02:50.661 T:7        info <general>: creating subdirectories
2025-04-03 19:02:50.661 T:7        info <general>: userdata folder: special://masterprofile/
2025-04-03 19:02:50.661 T:7        info <general>: recording folder: 
2025-04-03 19:02:50.661 T:7        info <general>: screenshots folder: 
2025-04-03 19:02:50.662 T:7        info <general>: Running database version Addons33
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.2sf v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.asap v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.fluidsynth v20.2.1 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.gme v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.gsf v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.hvl v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.modplug v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.ncsf v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.nosefart v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.openmpt v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.organya v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.qsf v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.sacd v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.sidplay v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.snesapu v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.ssf v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.stsound v21.0.0 installed
2025-04-03 19:02:50.706 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.timidity v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.upse v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.usf v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.vgmstream v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audiodecoder.wsr v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audioencoder.flac v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.aac v1.0.2 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.wma v1.0.2 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audioencoder.lame v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audioencoder.vorbis v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: audioencoder.wav v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: game.controller.default v1.0.42 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: game.controller.keyboard v1.1.43 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: game.controller.mouse v1.0.26 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: game.controller.snes v1.0.40 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: game.libretro v21.0.7 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: game.libretro.mrboom v5.5.0.161 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: imagedecoder.heif v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: imagedecoder.mpo v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: imagedecoder.raw v21.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: inputstream.adaptive v21.5.2 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: inputstream.ffmpegdirect v21.3.5 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: inputstream.rtmp v21.1.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.global.audioengine v1.1.1 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.global.filesystem v1.1.8 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.global.general v1.0.5 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.global.gui v5.15.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.global.main v2.0.2 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.global.network v1.0.4 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.global.tools v1.0.4 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.audiodecoder v4.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.audioencoder v3.0.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.game v3.0.2 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.imagedecoder v3.0.1 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.inputstream v3.3.0 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.peripheral v3.0.2 installed
2025-04-03 19:02:50.707 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.pvr v8.3.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.screensaver v2.2.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.vfs v3.0.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.videocodec v2.1.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: kodi.binary.instance.visualization v4.0.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: kodi.resource v1.0.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.album.universal v3.1.11 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.artists.universal v4.3.13 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.common.allmusic.com v3.2.2 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.common.fanart.tv v3.6.4 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.common.musicbrainz.org v2.2.4 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.common.theaudiodb.com v2.0.3 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.generic.albums v1.0.18 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.generic.artists v1.0.18 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.local v1.0.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.themoviedb.org.python v3.1.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: metadata.tvshows.themoviedb.org.python v1.7.2 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: peripheral.joystick v21.1.18 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: peripheral.xarcade v21.0.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.audio.arteconcert v2.0.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.audio.deutschlandfunk v2.0.8 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.audio.soundcloud v4.0.2 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.audio.spotify v1.3.10 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.amazon-test v1.1.5+matrix.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.ardundzdf v5.2.1+nexus installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.crunchyroll v3.3.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.filmarkivet v3.3.0+matrix.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.filmfriend v1.0.0 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.invidious v3.2.7 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.mubi v1.0.2 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.mytube v3.4.2 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.nasa v3.0.3+matrix.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.netflix v1.23.3+matrix.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.twitch v3.0.2 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.tyl0re.arte v1.1.3+matrix.1 installed
2025-04-03 19:02:50.708 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.weltspiegel v1.0.0 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: plugin.video.youtube v7.1.1.6 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.argustv v21.0.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.demo v21.0.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.dvblink v21.1.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.dvbviewer v21.1.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.filmon v21.0.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.freebox v21.0.0 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.hdhomerun v21.0.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.hts v21.2.5 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.iptvsimple v21.8.5 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.mediaportal.tvserver v21.0.3 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.mythtv v21.1.9 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.nextpvr v21.2.0 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.njoy v21.0.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.octonet v21.0.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.pctv v21.0.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.plutotv v21.3.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.sledovanitv.cz v21.3.0 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.stalker v21.1.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.teleboy v21.0.0 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.vbox v21.1.4 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.vdr.vnsi v21.1.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.vuplus v21.2.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.waipu v21.8.6 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.wmc v21.0.2 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: pvr.zattoo v21.0.3 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: repository.castagnait v2.0.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: repository.kodinerds v7.0.1.7 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: repository.lekma v4.0.1 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: repository.mtr81 v1.0 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: repository.sandmann79.plugins v1.0.4+matrix installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: repository.slyguy v0.0.9 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: repository.xbmc.org v3.4.0 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: resource.images.weathericons.default v1.1.9 installed
2025-04-03 19:02:50.709 T:7        info <general>: CAddonMgr::FindAddons: resource.language.en_gb v2.0.2 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: resource.uisounds.kodi v1.0.1 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.asteroids v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.asterwave v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.biogenesis v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.cpblobs v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.greynetic v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.matrixtrails v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.pingpong v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.pyro v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.shadertoy v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.stars v21.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.xbmc.builtin.black v1.0.34 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: screensaver.xbmc.builtin.dim v1.0.66 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.addon.signals v0.0.6+matrix.1 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.amazoncaptcha v0.5.11+matrix.1 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.beautifulsoup4 v4.12.2 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.certifi v2023.5.7 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.chardet v5.1.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.feedparser v6.0.11 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.iapc v2.4.2 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.idna v3.10.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.inputstreamhelper v0.7.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.kodi-six v0.1.3.1 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.libarte v2.0.2 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.libmediathek4 v1.0.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.mechanicalsoup v1.0.0+matrix.1 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.myconnpy v8.0.33 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.nuttig v1.4.2 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.pil v5.1.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.pyautogui v0.9.51+matrix.1 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.pycryptodome v3.4.3 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.python.twitch v3.0.2 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.pyxbmct v1.3.2+matrix.1 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.requests v2.31.0 installed
2025-04-03 19:02:50.710 T:7        info <general>: CAddonMgr::FindAddons: script.module.requests-cache v0.5.2+matrix.2 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.sgmllib3k v1.0.0+matrix.2 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.six v1.16.0+matrix.1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.slyguy v0.85.79 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.soupsieve v2.4.1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.urllib3 v2.2.3 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.xbmcswift2 v19.0.7 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.xmltodict v0.12.0+matrix.2 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: script.module.yt-dlp v2025.03.31-1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: service.manifests.mpd v1.4.2 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: service.upnext v1.1.9+matrix.1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: service.xbmc.versioncheck v0.5.30+matrix.1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: service.yt-dlp v1.4.4 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: skin.estuary v4.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: slyguy.dependencies v0.0.25 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: slyguy.disney.plus v0.20.13 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: vfs.libarchive v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: vfs.rar v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: vfs.sftp v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.fishbmc v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.goom v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.matrix v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.pictureit v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.projectm v21.0.1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.shadertoy v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.spectrum v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.starburst v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: visualization.waveform v21.0.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: webinterface.default v21.x-1.0.1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: xbmc.addon v21.1.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: xbmc.core v0.1.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: xbmc.gui v5.17.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: xbmc.json v13.5.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: xbmc.metadata v2.1.0 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: xbmc.python v3.0.1 installed
2025-04-03 19:02:50.711 T:7        info <general>: CAddonMgr::FindAddons: xbmc.webinterface v1.0.0 installed
2025-04-03 19:02:50.718 T:7        info <general>: CZeroconfBrowserAvahi::clientCallback: avahi server not available. But may become later...
2025-04-03 19:02:50.720 T:7        info <general>: Selected Logind/UPower as PowerSyscall
2025-04-03 19:02:50.739 T:7       error <general>: DBus error: org.freedesktop.DBus.Error.InvalidArgs - No such property “OnLowBattery”
2025-04-03 19:02:50.746 T:7        info <general>: CKeyboardLayoutManager: loading keyboard layouts from special://xbmc/system/keyboardlayouts...
2025-04-03 19:02:50.788 T:7        info <general>: InitWindowSystem: Connecting to Wayland server
2025-04-03 19:02:50.788 T:7        info <general>: Wayland presentation clock: 1
2025-04-03 19:02:50.788 T:7        info <general>: UpdateResolutions: User wanted output "Default", we now have "Apple Computer Inc iMac" size 475x267 mm with 1 mode(s):
2025-04-03 19:02:50.788 T:7        info <general>: UpdateResolutions: - 3840x2160 @59.997 Hz pixel ratio 1.001 current
2025-04-03 19:02:50.806 T:7        info <general>: EGL_VERSION = 1.5
2025-04-03 19:02:50.806 T:7        info <general>: EGL_VENDOR = Mesa Project
2025-04-03 19:02:50.806 T:7        info <general>: EGL_EXTENSIONS = EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_config_select_group EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_present_opaque EGL_EXT_query_reset_notification_strategy EGL_EXT_surface_compression EGL_EXT_swap_buffers_with_damage EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_gl_interop EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_MESA_x11_native_visual_id EGL_WL_bind_wayland_display EGL_WL_create_wayland_buffer_from_image 
2025-04-03 19:02:50.806 T:7        info <general>: EGL_CLIENT_EXTENSIONS = EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_explicit_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_EXT_platform_xcb EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
2025-04-03 19:02:50.806 T:7        info <general>: RetroPlayer[RENDER]: Registering renderer factory for DMA
2025-04-03 19:02:50.806 T:7        info <general>: RetroPlayer[RENDER]: Registering renderer factory for OpenGL
2025-04-03 19:02:50.828 T:7        info <general>: VAAPI::Close - closing decoder context
2025-04-03 19:02:50.829 T:7        info <general>: CApplication::CreateGUI - using the wayland windowing system
2025-04-03 19:02:50.829 T:7        info <general>: Checking resolution 16
2025-04-03 19:02:50.829 T:7        info <general>: CreateNewWindow: Starting full screen size 3840x2160
2025-04-03 19:02:50.829 T:7        info <general>: UpdateSizeVariables: Surface size changed: 0x0 -> 3840x2160
2025-04-03 19:02:50.829 T:7        info <general>: UpdateSizeVariables: Buffer size changed: 0x0 -> 3840x2160
2025-04-03 19:02:50.829 T:7        info <general>: UpdateSizeVariables: Configured size changed: 0x0 -> 3840x2160
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1816:47: unrecognized keysym "XF86EmojiPicker"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1817:47: unrecognized keysym "XF86Dictate"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1818:54: unrecognized keysym "XF86CameraAccessEnable"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1819:55: unrecognized keysym "XF86CameraAccessDisable"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1820:54: unrecognized keysym "XF86CameraAccessToggle"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1825:58: unrecognized keysym "XF86KbdInputAssistPrevgrou"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1826:58: unrecognized keysym "XF86KbdInputAssistNextgrou"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1850:47: unrecognized keysym "XF86NextElement"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1851:51: unrecognized keysym "XF86PreviousElement"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1852:57: unrecognized keysym "XF86AutopilotEngageToggle"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1853:48: unrecognized keysym "XF86MarkWaypoint"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1854:47: unrecognized keysym "XF86Sos"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1855:47: unrecognized keysym "XF86NavChart"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1856:48: unrecognized keysym "XF86FishingChart"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1857:52: unrecognized keysym "XF86SingleRangeRadar"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1858:50: unrecognized keysym "XF86DualRangeRadar"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1859:48: unrecognized keysym "XF86RadarOverlay"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1860:52: unrecognized keysym "XF86TraditionalSonar"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1861:48: unrecognized keysym "XF86ClearvuSonar"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1862:47: unrecognized keysym "XF86SidevuSonar"
                                                   
2025-04-03 19:02:50.831 T:7     warning <general>: [xkb] (input string):1863:47: unrecognized keysym "XF86NavInfo"
                                                   
2025-04-03 19:02:50.833 T:7       error <general>: [xkb] /usr/share/X11/locale/en_US.UTF-8/Compose:1661:1: unrecognized keysym "dead_hamza" on left-hand side
                                                   
2025-04-03 19:02:50.833 T:7       error <general>: [xkb] /usr/share/X11/locale/en_US.UTF-8/Compose:1662:1: unrecognized keysym "dead_hamza" on left-hand side
                                                   
2025-04-03 19:02:50.833 T:7       error <general>: [xkb] /usr/share/X11/locale/en_US.UTF-8/Compose:1663:1: unrecognized keysym "dead_hamza" on left-hand side
                                                   
2025-04-03 19:02:50.833 T:7       error <general>: [xkb] /usr/share/X11/locale/en_US.UTF-8/Compose:1664:1: unrecognized keysym "dead_hamza" on left-hand side
                                                   
2025-04-03 19:02:50.833 T:7       error <general>: [xkb] /usr/share/X11/locale/en_US.UTF-8/Compose:1665:1: unrecognized keysym "dead_hamza" on left-hand side
                                                   
2025-04-03 19:02:50.834 T:7        info <general>: UpdateSizeVariables: Surface size changed: 3840x2160 -> 1920x1080
2025-04-03 19:02:50.834 T:7        info <general>: UpdateSizeVariables: Buffer size changed: 3840x2160 -> 1920x1080
2025-04-03 19:02:50.834 T:7        info <general>: UpdateSizeVariables: Configured size changed: 3840x2160 -> 1920x1080
2025-04-03 19:02:50.839 T:7        info <general>: CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 24.3.4 (git-769e51468b), Major: 4, Minor: 6
2025-04-03 19:02:50.839 T:7        info <general>: GL_VENDOR = AMD
2025-04-03 19:02:50.839 T:7        info <general>: GL_RENDERER = AMD Radeon RX Graphics (radeonsi, polaris11, LLVM 17.0.6, DRM 3.61, 6.14.0-x64v3-xanmod1)
2025-04-03 19:02:50.839 T:7        info <general>: GL_VERSION = 4.6 (Core Profile) Mesa 24.3.4 (git-769e51468b)
2025-04-03 19:02:50.839 T:7        info <general>: GL_SHADING_LANGUAGE_VERSION = 4.60
2025-04-03 19:02:50.839 T:7        info <general>: GL_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX = 6110428
2025-04-03 19:02:50.839 T:7        info <general>: GL_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX = 2097152
2025-04-03 19:02:50.839 T:7        info <general>: GL_EXTENSIONS = GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_multisample_advanced GL_AMD_gpu_shader_int64 GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_filter_minmax GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_meminfo GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_EGL_image_storage GL_EXT_EGL_image_storage_compression GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_debug_label GL_EXT_demote_to_helper_invocation GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_filter_minmax GL_EXT_texture_integer GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_IBM_multimode_draw_arrays GL_INTEL_blackhole_render GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_shader_subgroup GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_framebuffer_flip_y GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_const_bandwidth GL_MESA_texture_signed_rgba GL_NVX_gpu_memory_info GL_NV_alpha_to_coverage_dither_control GL_NV_compute_shader_derivatives GL_NV_conditional_render GL_NV_copy_image GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_shader_atomic_int64 GL_NV_texture_barrier GL_NV_vdpau_interop GL_OES_EGL_image GL_S3_s3tc 
2025-04-03 19:02:50.848 T:7        info <general>: SetResolutionExternal: Kodi asked to switch mode to 1920x1080 @59.997 Hz on output "Apple Computer Inc iMac" full screen
2025-04-03 19:02:50.849 T:7        info <general>: GetOSScreenSaverImpl: Using idle-inhibit-unstable-v1 protocol for screen saver inhibition
2025-04-03 19:02:50.908 T:7        info <general>: GL: Enabling VSYNC
2025-04-03 19:02:50.909 T:7        info <general>: UpdateResolutions: User wanted output "Default", we now have "Apple Computer Inc iMac" size 475x267 mm with 1 mode(s):
2025-04-03 19:02:50.909 T:7        info <general>: UpdateResolutions: - 3840x2160 @59.997 Hz pixel ratio 1.001 current
2025-04-03 19:02:50.909 T:7        info <general>: load keymapping
2025-04-03 19:02:50.910 T:7        info <general>: Loading special://xbmc/system/keymaps/appcommand.xml
2025-04-03 19:02:50.910 T:7        info <general>: Loading special://xbmc/system/keymaps/customcontroller.AppleRemote.xml
2025-04-03 19:02:50.910 T:7        info <general>: Loading special://xbmc/system/keymaps/customcontroller.Harmony.xml
2025-04-03 19:02:50.910 T:7        info <general>: Loading special://xbmc/system/keymaps/customcontroller.SiriRemote.xml
2025-04-03 19:02:50.910 T:7        info <general>: Loading special://xbmc/system/keymaps/gamepad.xml
2025-04-03 19:02:50.911 T:7        info <general>: Loading special://xbmc/system/keymaps/joystick.xml
2025-04-03 19:02:50.911 T:7        info <general>: Loading special://xbmc/system/keymaps/keyboard.xml
2025-04-03 19:02:50.912 T:7        info <general>: Loading special://xbmc/system/keymaps/mouse.xml
2025-04-03 19:02:50.912 T:7        info <general>: Loading special://xbmc/system/keymaps/remote.xml
2025-04-03 19:02:50.913 T:7        info <general>: Loading special://xbmc/system/keymaps/touchscreen.xml
2025-04-03 19:02:50.913 T:7        info <general>: GUI format 3840x2160, Display Apple Computer Inc iMac: 3840x2160 @ 60.00Hz
2025-04-03 19:02:50.933 T:42       info <general>: CAESinkALSA - Unable to open device "oss" for playback
2025-04-03 19:02:50.939 T:42       info <general>: CAESinkALSA - Unable to open device "upmix" for playback
2025-04-03 19:02:50.939 T:42       info <general>: CAESinkALSA - Unable to open device "vdownmix" for playback
2025-04-03 19:02:50.942 T:42       info <general>: CAESinkALSA - Unable to open device "sysdefault:CARD=PCH" for playback
2025-04-03 19:02:50.942 T:42       info <general>: CAESinkALSA - Unable to open device "default:CARD=PCH" for playback
2025-04-03 19:02:50.942 T:42       info <general>: CAESinkALSA - Unable to open device "front:CARD=PCH" for playback
2025-04-03 19:02:50.942 T:42       info <general>: CAESinkALSA - Unable to open device "surround21:CARD=PCH" for playback
2025-04-03 19:02:50.942 T:42       info <general>: CAESinkALSA - Unable to open device "usbstream:CARD=PCH" for playback
2025-04-03 19:02:50.960 T:42       info <general>: CAESinkALSA - Unable to open device "usbstream:CARD=HDMI" for playback
2025-04-03 19:02:50.960 T:42       info <general>: CAESinkALSA - Unable to open device "sysdefault:CARD=HC6" for playback
2025-04-03 19:02:50.961 T:42       info <general>: Skipped 1 duplicate messages..
2025-04-03 19:02:50.961 T:42       info <general>: CAESinkALSA - Unable to open device "default:CARD=HC6" for playback
2025-04-03 19:02:50.961 T:42       info <general>: CAESinkALSA - Unable to open device "front:CARD=HC6,DEV=0" for playback
2025-04-03 19:02:50.961 T:42       info <general>: CAESinkALSA - Unable to open device "surround21:CARD=HC6,DEV=0" for playback
2025-04-03 19:02:50.961 T:42       info <general>: CAESinkALSA - Unable to open device "iec958:CARD=HC6,DEV=0" for playback
2025-04-03 19:02:50.961 T:42       info <general>: CAESinkALSA - Unable to open device "usbstream:CARD=HC6" for playback
2025-04-03 19:02:50.962 T:42       info <general>: Found 1 Lists of Devices
2025-04-03 19:02:50.962 T:42       info <general>: Enumerated ALSA devices:
2025-04-03 19:02:50.962 T:42       info <general>:     Device 1
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : default
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : Default ALSA Output (currently PulseAudio Sound Server)
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: 
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR, BL, BR, FC, LFE, SL, SR, UNKNOWN1, UNKNOWN2, UNKNOWN3, UNKNOWN4, UNKNOWN5, UNKNOWN6, UNKNOWN7, UNKNOWN8
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_U8
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : No passthrough capabilities
2025-04-03 19:02:50.962 T:42       info <general>:     Device 2
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : pulse
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : PulseAudio Sound Server
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: 
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR, BL, BR, FC, LFE, SL, SR, UNKNOWN1, UNKNOWN2, UNKNOWN3, UNKNOWN4, UNKNOWN5, UNKNOWN6, UNKNOWN7, UNKNOWN8
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE,AE_FMT_U8
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : No passthrough capabilities
2025-04-03 19:02:50.962 T:42       info <general>:     Device 3
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=0
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : HDA ATI
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: HDMI #0
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2025-04-03 19:02:50.962 T:42       info <general>:     Device 4
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=1
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : HDA ATI
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: HDMI #1
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2025-04-03 19:02:50.962 T:42       info <general>:     Device 5
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=2
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : HDA ATI
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: HDMI #2
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2025-04-03 19:02:50.962 T:42       info <general>:     Device 6
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=3
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : HDA ATI
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: HDMI #3
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2025-04-03 19:02:50.962 T:42       info <general>:     Device 7
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=4
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : HDA ATI
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: HDMI #4
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2025-04-03 19:02:50.962 T:42       info <general>:     Device 8
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=5
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayName     : HDA ATI
2025-04-03 19:02:50.962 T:42       info <general>:         m_displayNameExtra: HDMI #5
2025-04-03 19:02:50.962 T:42       info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2025-04-03 19:02:50.962 T:42       info <general>:         m_channels        : FL, FR
2025-04-03 19:02:50.962 T:42       info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2025-04-03 19:02:50.962 T:42       info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2025-04-03 19:02:50.962 T:42       info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2025-04-03 19:02:50.962 T:43       info <general>: CActiveAESink::OpenSink - initialize sink
2025-04-03 19:02:50.962 T:43       info <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2025-04-03 19:02:50.965 T:43       info <general>: CAESinkALSA::Initialize - Opened device "default"
2025-04-03 19:02:51.001 T:7        info <general>: CLangInfo: loading resource.language.en_gb language information...
2025-04-03 19:02:51.002 T:7        info <general>: global locale set to en_US.UTF-8
2025-04-03 19:02:51.002 T:7        info <general>: CLangInfo: loading resource.language.en_gb language strings...
2025-04-03 19:02:51.020 T:48       info <general>: Running database version Addons33
2025-04-03 19:02:51.020 T:48       info <general>: Running database version ViewModes6
2025-04-03 19:02:51.020 T:48       info <general>: Running database version Textures13
2025-04-03 19:02:51.021 T:48       info <general>: Running database version MyMusic83
2025-04-03 19:02:51.022 T:48       info <general>: Running database version MyVideos131
2025-04-03 19:02:51.022 T:48       info <general>: Running database version TV46
2025-04-03 19:02:51.023 T:48       info <general>: Running database version Epg16
2025-04-03 19:02:51.045 T:7        info <general>: Unloaded skin
2025-04-03 19:02:51.046 T:7        info <general>:   load skin from: /app/share/kodi/addons/skin.estuary/ (version: 4.0.0)
2025-04-03 19:02:51.046 T:7        info <general>:   load fonts for skin...
2025-04-03 19:02:51.046 T:7        info <general>: Loading colors from /app/share/kodi/addons/skin.estuary/colors/concrete.xml
2025-04-03 19:02:51.046 T:7        info <general>: Loading skin includes from /app/share/kodi/addons/skin.estuary/xml/Includes.xml
2025-04-03 19:02:51.064 T:7        info <general>: LoadFontsFromFile: Loading <fontset> with name 'Default' from '/app/share/kodi/addons/skin.estuary/xml/Font.xml'
2025-04-03 19:02:51.068 T:7        info <general>: LoadTimers: Trying to load skin timers from /app/share/kodi/addons/skin.estuary/xml/Timers.xml
2025-04-03 19:02:51.068 T:7        info <general>:   load new skin...
2025-04-03 19:02:51.068 T:7        info <general>: Loading custom window XMLs from skin path /app/share/kodi/addons/skin.estuary/xml
2025-04-03 19:02:51.070 T:7        info <general>:   initialize new skin...
2025-04-03 19:02:51.070 T:7        info <general>: Loading skin file: Custom_1109_TopBarOverlay.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.074 T:7        info <general>: Loading skin file: DialogBusy.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.074 T:7        info <general>: Loading skin file: DialogNotification.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.074 T:7        info <general>: Loading skin file: DialogSeekBar.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.079 T:7        info <general>: Loading skin file: DialogExtendedProgressBar.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.080 T:7        info <general>: Loading skin file: Pointer.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.080 T:7        info <general>: Loading skin file: DialogBusy.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.080 T:7        info <general>: Loading skin file: DialogVolumeBar.xml, load type: LOAD_ON_GUI_INIT
2025-04-03 19:02:51.081 T:7        info <general>: Loading resource://resource.uisounds.kodi/sounds.xml
2025-04-03 19:02:51.090 T:7        info <general>:   skin loaded...
2025-04-03 19:02:51.090 T:7        info <general>: Loading skin file: Startup.xml, load type: LOAD_EVERY_TIME
2025-04-03 19:02:51.090 T:7        info <general>: Loading skin file: MyFavourites.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:02:51.111 T:7     warning <general>: JSONRPC: Could not parse type "Setting.Details.SettingList"
2025-04-03 19:02:51.111 T:7        info <general>: JSONRPC: Adding type "Setting.Details.SettingList" to list of incomplete definitions (waiting for "Setting.Details.Setting")
2025-04-03 19:02:51.111 T:7        info <general>: JSONRPC: Resolving incomplete types/methods referencing Setting.Details.Setting
2025-04-03 19:02:51.116 T:7        info <general>: JSONRPC v13.5.0: Successfully initialized
2025-04-03 19:02:51.116 T:7        info <general>: [Media Detection] starting service for optical media detection
2025-04-03 19:02:51.119 T:7        info <general>: AddOnLog: peripheral.joystick: Enabling joystick interface "linux"
2025-04-03 19:02:51.120 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:02:51.120 T:7        info <general>: Register - new keyboard device registered on application->keyboard: Keyboard (0000:0000)
2025-04-03 19:02:51.120 T:7        info <general>: Register - new mouse device registered on application->mouse: Mouse (0000:0000)
2025-04-03 19:02:51.120 T:7        info <general>: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
2025-04-03 19:02:51.120 T:7        info <general>: Loaded playercorefactory configuration
2025-04-03 19:02:51.120 T:7        info <general>: Loading player core factory settings from special://profile/playercorefactory.xml.
2025-04-03 19:02:51.120 T:7        info <general>: Loaded playercorefactory configuration
2025-04-03 19:02:51.120 T:7        info <general>: removing tempfiles
2025-04-03 19:02:51.121 T:48       info <general>: UpdateClients: Creating PVR client: addonId=pvr.dvblink, instanceId=0, clientId=1
2025-04-03 19:02:51.123 T:7        info <general>: initialize done
2025-04-03 19:02:51.123 T:7        info <general>: Running the application...
2025-04-03 19:02:51.124 T:67       info <general>: ES: Starting UDP Event server on port 9777
2025-04-03 19:02:51.124 T:67       info <general>: UDP: Listening on port 9777 (ipv6 : false)
2025-04-03 19:02:51.127 T:67       info <general>: CZeroconfAvahi::clientCallback: avahi server not available. But may become later...
2025-04-03 19:02:51.135 T:48       info <general>: AddOnLog: pvr.dvblink: Generated guid 00f9d5bd-3b06-df9b-3b28-e61f30e2b014 to use as a DVBLink client ID
2025-04-03 19:02:51.153 T:48       info <general>: AddOnLog: pvr.dvblink: Connected to DVBLink Server '127.0.0.1'
2025-04-03 19:02:51.169 T:7        info <general>: JSONRPC Server: Successfully initialized
2025-04-03 19:02:51.170 T:7        info <general>: CWSDiscoveryListenerUDP::Start - Started
2025-04-03 19:02:51.170 T:48       info <general>: PVR Manager: Starting
2025-04-03 19:02:51.180 T:74       info <general>: AddOnLog: pvr.dvblink: Getting channels (63 channels on server)
2025-04-03 19:02:51.196 T:74       info <general>: Skipped 1 duplicate messages..
2025-04-03 19:02:51.196 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 timers
2025-04-03 19:02:51.198 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 schedules
2025-04-03 19:02:51.202 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 recordings
2025-04-03 19:02:51.252 T:74       info <general>: PVR Manager: Started
2025-04-03 19:02:51.261 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 timers
2025-04-03 19:02:51.264 T:77       info <general>: AddOnLog: pvr.dvblink: Not EPG data found for channel with id : 153
2025-04-03 19:02:51.264 T:77      error <general>: GetEPGForChannel: Add-on 1 returned an error: the command failed
2025-04-03 19:02:51.264 T:77      error <general>: Update: Failed to update table 'ZDF HD'
2025-04-03 19:02:51.264 T:7        info <general>: GL: Maximum texture width: 16384
2025-04-03 19:02:51.264 T:7        info <general>: Loading controller layout: /app/share/kodi/addons/game.controller.mouse/resources/layout.xml
2025-04-03 19:02:51.266 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 schedules
2025-04-03 19:02:51.268 T:77       info <general>: AddOnLog: pvr.dvblink: Not EPG data found for channel with id : 154
2025-04-03 19:02:51.268 T:77      error <general>: GetEPGForChannel: Add-on 1 returned an error: the command failed
2025-04-03 19:02:51.268 T:77      error <general>: Update: Failed to update table 'ZDFinfo HD'
2025-04-03 19:02:51.271 T:77       info <general>: AddOnLog: pvr.dvblink: Not EPG data found for channel with id : 155
2025-04-03 19:02:51.271 T:77      error <general>: GetEPGForChannel: Add-on 1 returned an error: the command failed
2025-04-03 19:02:51.271 T:77      error <general>: Update: Failed to update table 'zdf_neo HD'
2025-04-03 19:02:51.273 T:77       info <general>: AddOnLog: pvr.dvblink: Not EPG data found for channel with id : 157
2025-04-03 19:02:51.273 T:77      error <general>: GetEPGForChannel: Add-on 1 returned an error: the command failed
2025-04-03 19:02:51.273 T:77      error <general>: Update: Failed to update table 'KiKA HD'
2025-04-03 19:02:51.278 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 timers
2025-04-03 19:02:51.280 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 schedules
2025-04-03 19:02:51.291 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 timers
2025-04-03 19:02:51.293 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 schedules
2025-04-03 19:02:51.317 T:7        info <general>: UpdateSizeVariables: Buffer size changed: 1920x1080 -> 3840x2160
2025-04-03 19:02:51.317 T:7        info <general>: UpdateSizeVariables: Buffer scale changed: 1 -> 2
2025-04-03 19:02:51.317 T:7        info <general>: ApplyBufferScale: Setting Wayland buffer scale to 2
2025-04-03 19:02:51.319 T:7        info <general>: GL: Maximum texture width: 16384
2025-04-03 19:02:51.627 T:56       info <general>: plugin.audio.spotify:service:<module>: Python version: 3.11.11 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0].
2025-04-03 19:02:51.627 T:56       info <general>: plugin.audio.spotify:service:<module>: Python exe: /usr/bin/python3.
2025-04-03 19:02:51.654 T:13       info <general>: Loading special://xbmc/system/Lircmap.xml
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'mceusb'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'XboxDVDDongle'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'Microsoft_Xbox'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'PinnacleSysPCTVRemote'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'anysee'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'iMON-PAD'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'Antec_Veris_RM200'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'MCE_via_iMON'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'TwinHanRemote'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'linux-input-layer'
2025-04-03 19:02:51.654 T:13       info <general>: * Linking remote mapping for 'linux-input-layer' to 'cx23885_remote'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'mediacenter'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'devinput'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'devinput-32'
2025-04-03 19:02:51.654 T:13       info <general>: * Adding remote mapping for device 'devinput-64'
2025-04-03 19:02:51.672 T:64       info <general>: [service.upnext] UpNextMonitor -> Service started
2025-04-03 19:02:51.718 T:56       info <general>: plugin.audio.spotify:service:<module>: Platform: Linux-6.14.0-x64v3-xanmod1-x86_64-with-glibc2.38.
2025-04-03 19:02:51.985 T:59       info <general>: [plugin.video.netflix (0)] The debug logging is set as DISABLED
2025-04-03 19:02:52.414 T:63       info <general>: [service.manifests.mpd] <service> starting...
2025-04-03 19:02:52.420 T:57       info <general>: [Amazon VOD] Service: Proxy bound to 127.0.0.1:49077
2025-04-03 19:02:52.421 T:57       info <general>: [Amazon VOD] Service: Proxy server started
2025-04-03 19:02:52.421 T:57       info <general>: [Amazon VOD] Service started
2025-04-03 19:02:52.434 T:63       info <general>: [service.manifests.mpd] <service.httpd> started on: http://127.0.0.1:49411
2025-04-03 19:02:53.056 T:74       info <general>: AddOnLog: pvr.dvblink: Found 0 recordings
2025-04-03 19:02:53.178 T:7        info <general>: Loading skin file: Home.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:02:53.270 T:60       info <general>: Twitch: Service: Start
2025-04-03 19:02:53.333 T:56       info <general>: plugin.audio.spotify:main_service:__init__: Spotify plugin version: 1.3.10.
2025-04-03 19:02:53.369 T:56       info <general>: plugin.audio.spotify:spotty_helper:__get_linux_spotty_path: Reported architecture: 'x86_64'.
2025-04-03 19:02:53.371 T:56       info <general>: plugin.audio.spotify:spotty_helper:__get_spotty_path: Spotty architecture detected. Using spotty binary '/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64'.
2025-04-03 19:02:53.382 T:56       info <general>: plugin.audio.spotify:http_video_player_setter:set_http_rule: There is already a video http rule in '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/playercorefactory.xml'. Nothing to do.
2025-04-03 19:02:53.387 T:56       info <general>: plugin.audio.spotify:main_service:run: Starting main service loop.
2025-04-03 19:02:53.389 T:56       info <general>: plugin.audio.spotify:main_service:run: Started bottle with port 52308.
2025-04-03 19:02:53.396 T:56       info <general>: plugin.audio.spotify:spotty_auth:renew_token: Retrieving auth token....
2025-04-03 19:02:53.401 T:88       info <general>: plugin.audio.spotify:bottle_manager:__bottle_stderr: ('Bottle v0.13-dev server starting up (using MyWSGIRefServer())...',)
2025-04-03 19:02:53.403 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:02:53.405 T:88       info <general>: plugin.audio.spotify:bottle_manager:__bottle_stderr: ('Listening on http://localhost:52308/',)
2025-04-03 19:02:53.408 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:02:53.409 T:88       info <general>: plugin.audio.spotify:bottle_manager:__bottle_stderr: ('Hit Ctrl-C to quit.\n',)
2025-04-03 19:02:53.416 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:02:53.416 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:02:53.437 T:88       info <general>: plugin.audio.spotify:bottle_manager:run: Starting wsgiref web server, timeout = 600.
2025-04-03 19:02:53.438 T:62       info <general>: script.module.slyguy - Shared Service: Started
2025-04-03 19:02:53.438 T:62       info <general>: script.module.slyguy - Python Version: 3.11.11 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0]
2025-04-03 19:02:53.499 T:62       info <general>: script.module.slyguy - Proxy Started: http://127.0.0.1:8095/
2025-04-03 19:02:53.501 T:62       info <general>: script.module.slyguy - Visit donate.slyguy.uk to become a supporter and unlock perks!
2025-04-03 19:02:53.503 T:62       info <general>: script.module.slyguy - Widevine Level (fallback): 3
2025-04-03 19:02:53.503 T:62       info <general>: script.module.slyguy - HDCP Level (fallback): 0.0
2025-04-03 19:02:53.516 T:61       info <general>: [plugin.video.youtube] Service: Starting v7.1.1.6
                                                   	Kodi:   v21.1 (Kodi Omega)
                                                   	Python: v3.11.11
2025-04-03 19:02:54.419 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:02:54.426 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:02:54.431 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:02:54.431 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:02:54.595 T:7        info <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:02:54.762 T:66       info <general>: [service.yt-dlp] <service> starting...
2025-04-03 19:02:54.763 T:66       info <general>: [service.yt-dlp] <service> Include automatic captions: False
2025-04-03 19:02:54.763 T:66       info <general>: [service.yt-dlp] <service.mpd> Limit framerate: No limit
2025-04-03 19:02:54.763 T:66       info <general>: [service.yt-dlp] <service.mpd> Framerate hinting: Integer
2025-04-03 19:02:54.763 T:66       info <general>: [service.yt-dlp] <service.mpd> Exclude codecs: None
2025-04-03 19:02:54.930 T:58       info <general>: [plugin.video.mytube] <service> starting...
2025-04-03 19:02:54.932 T:58       info <general>: [plugin.video.mytube] <service.session> Timeout: (9.05, 10.0)
2025-04-03 19:02:54.932 T:58       info <general>: [plugin.video.mytube] <service.session> Accept cookies: False
2025-04-03 19:02:54.932 T:58       info <general>: [plugin.video.mytube] <service.session> Language: English (US)
2025-04-03 19:02:54.932 T:58       info <general>: [plugin.video.mytube] <service.session> Location: United States
2025-04-03 19:02:54.933 T:58       info <general>: [plugin.video.mytube] <service.session.ytdlp> Include automatic captions: False
2025-04-03 19:02:54.933 T:58       info <general>: [plugin.video.mytube] <service.session.ytdlp> Limit framerate: No limit
2025-04-03 19:02:54.933 T:58       info <general>: [plugin.video.mytube] <service.session.ytdlp> Framerate hinting: Integer
2025-04-03 19:02:54.934 T:58       info <general>: [plugin.video.mytube] <service.session.ytdlp> Exclude codecs: None
2025-04-03 19:02:54.934 T:58       info <general>: [plugin.video.mytube] <service.search> Search history: True
2025-04-03 19:02:54.935 T:58       info <general>: [plugin.video.mytube] <service.search> Query type: All
2025-04-03 19:02:54.935 T:58       info <general>: [plugin.video.mytube] <service.search> Sort order: Relevance
2025-04-03 19:02:55.433 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:02:55.434 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:02:55.437 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:02:55.437 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:02:55.817 T:7        info <general>: Loading skin file: AddonBrowser.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:02:56.120 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:02:56.442 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:02:56.445 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:02:56.452 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:02:56.452 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:02:57.456 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:02:57.459 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:02:57.468 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:02:57.468 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:02:58.472 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:02:58.475 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:02:58.487 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:02:58.487 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:02:59.491 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:02:59.495 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:02:59.506 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:02:59.506 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:00.510 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:00.514 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:00.523 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:00.523 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:01.120 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:03:01.526 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:01.530 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:01.539 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:01.539 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:02.542 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:02.546 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:02.555 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:02.555 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:02.942 T:7        info <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:03:03.559 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:03.564 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:03.573 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:03.573 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:04.579 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:04.583 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:04.592 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:04.592 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:04.867 T:7     warning <general>: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
2025-04-03 19:03:04.871 T:7     warning <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2025-04-03 19:03:05.597 T:56       info <general>: Skipped 78 duplicate messages..
2025-04-03 19:03:05.597 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:05.600 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:05.609 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:05.609 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:06.120 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:03:06.611 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:06.611 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:06.614 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:06.614 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:07.618 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:07.621 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:07.629 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:07.629 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:08.633 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:08.637 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:08.646 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:08.646 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:08.712 T:48      error <general>: CCurlFile::Open - <https://github.com/CastagnaIT/repository.castagnait/raw/kodi/kodi19/repository.castagnait/icon.jpg> Failed with code 404:
                                                   
2025-04-03 19:03:09.388 T:7        info <general>: Skipped 1 duplicate messages..
2025-04-03 19:03:09.388 T:7        info <general>: Loading skin file: DialogAddonInfo.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:03:09.474 T:48      error <general>: CCurlFile::Open - <https://github.com/CastagnaIT/repository.castagnait/raw/kodi/kodi19/repository.castagnait/icon.jpg> Failed with code 404:
                                                   
2025-04-03 19:03:09.650 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:09.653 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:09.665 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:09.665 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:10.668 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:10.671 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:10.681 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:10.681 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:11.121 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:03:11.685 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:11.688 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:11.697 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:11.697 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:12.701 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:12.705 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:12.714 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:12.714 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:12.774 T:7        info <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:03:13.717 T:56    warning <general>: plugin.audio.spotify:spotty_auth:__get_retry_auth_token: Took 20 retries to get authorization token.
2025-04-03 19:03:13.721 T:56      error <general>: plugin.audio.spotify:main_service:__renew_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/main_service.py", line 125, in __renew_token
                                                       self.__spotty_auth.renew_token()
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 94, in renew_token
                                                       f"Could not get Spotify auth token for" f" user '{utils.get_username()}'."
                                                                                                         ^^^^^^^^^^^^^^^^^^^^
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/utils.py", line 55, in get_username
                                                       raise Exception("Could not get spotify username.")
                                                    Exception: Could not get spotify username.
                                                   
2025-04-03 19:03:13.721 T:56      error <general>: plugin.audio.spotify:main_service:__renew_token: Exception --> Could not renew Spotify auth token.
2025-04-03 19:03:13.723 T:56       info <general>: plugin.audio.spotify:main_service:run: Spotify not yet authorized.
2025-04-03 19:03:13.724 T:56       info <general>: plugin.audio.spotify:main_service:run: Refreshing auth token now.
2025-04-03 19:03:13.726 T:56       info <general>: plugin.audio.spotify:spotty_auth:renew_token: Retrieving auth token....
2025-04-03 19:03:13.729 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:13.733 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:13.741 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:13.741 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:14.556 T:7        info <general>: Loading controller layout: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/game.controller.keyboard/resources/layout.xml
2025-04-03 19:03:14.745 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:14.749 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:14.764 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:14.764 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:14.956 T:7     warning <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2025-04-03 19:03:15.768 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:15.772 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:15.783 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:15.783 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:16.121 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:03:16.787 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:16.790 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:16.800 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:16.800 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:17.805 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:17.809 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:17.818 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:17.818 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:18.822 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:18.826 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:18.836 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:18.836 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:19.840 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:19.844 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:19.853 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:19.853 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:19.936 T:7        info <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY
2025-04-03 19:03:20.857 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:20.860 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:20.869 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:20.869 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:21.121 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:03:21.873 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:21.876 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:21.885 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:21.885 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:22.060 T:74       info <general>: PVR Manager: Starting cleanup of cached images.
2025-04-03 19:03:22.144 T:7        info <general>: Stopping the application...
2025-04-03 19:03:22.144 T:7        info <general>: Stopping player
2025-04-03 19:03:22.144 T:7        info <general>: Storing total System Uptime
2025-04-03 19:03:22.144 T:7        info <general>: Saving settings
2025-04-03 19:03:22.147 T:7        info <general>: Saving skin settings
2025-04-03 19:03:22.147 T:7        info <general>: Stopping all
2025-04-03 19:03:22.147 T:7        info <general>: ES: Stopping event server
2025-04-03 19:03:22.148 T:74       info <general>: PVR Manager: Cleaned up 0 cached images.
2025-04-03 19:03:22.156 T:67       info <general>: ES: UDP Event server stopped
2025-04-03 19:03:22.890 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:22.893 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:22.906 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:22.906 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:23.281 T:7        info <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2025-04-03 19:03:23.281 T:7        info <general>: Stopping zeroconf browser
2025-04-03 19:03:23.283 T:7        info <general>: CServiceAddonManager: failed to stop inputstream.ffmpegdirect (may have ended)
2025-04-03 19:03:23.907 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:23.908 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:23.910 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:23.910 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:24.914 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:24.918 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:24.928 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:24.928 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:25.929 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:25.930 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:25.933 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:25.933 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:26.121 T:53      error <general>: AddOnLog: peripheral.xarcade: Failed to open event devices
2025-04-03 19:03:26.937 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:26.941 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:26.950 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:26.950 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:27.954 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Running spotty...
2025-04-03 19:03:27.957 T:56       info <general>: plugin.audio.spotify:spotty:run_spotty: Spotty args: /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/deps/spotty/x86-linux/spotty-x86_64 --cache /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache --verbose --name Kodi-Spotty --client-id 2eb96f9b37494be1824999d58028a305 --scope user-read-playback-state,user-read-currently-playing,user-modify-playback-state,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,user-follow-modify,user-follow-read,user-library-read,user-library-modify,user-read-private,user-read-email,user-top-read --save-token /home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token
2025-04-03 19:03:27.966 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Traceback (most recent call last):
                                                      File "/home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/resources/lib/spotty_auth.py", line 143, in __get_token
                                                       with open(self.__spotty.get_spotty_token_file()) as f:
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    FileNotFoundError: [Errno 2] No such file or directory: '/home/localhost/.var/app/tv.kodi.Kodi/data/userdata/addon_data/plugin.audio.spotify/spotty-cache/spotty-token'
                                                   
2025-04-03 19:03:27.966 T:56      error <general>: plugin.audio.spotify:spotty_auth:__get_token: Exception --> Get Spotify token error.
2025-04-03 19:03:28.294 T:7       error <general>: CPythonInvoker(1, /home/localhost/.var/app/tv.kodi.Kodi/data/addons/plugin.audio.spotify/service.py): script didn't stop in 5 seconds - let's kill it
2025-04-03 19:03:28.295 T:57       info <general>: [Amazon VOD] Service stopped
2025-04-03 19:03:28.477 T:57       info <general>: [Amazon VOD] Service: Proxy server stopped
2025-04-03 19:03:28.507 T:58       info <general>: [plugin.video.mytube] <service.feed> stopped
2025-04-03 19:03:28.507 T:58       info <general>: [plugin.video.mytube] <service.search> stopped
2025-04-03 19:03:28.507 T:58       info <general>: [plugin.video.mytube] <service.browse> stopped
2025-04-03 19:03:28.507 T:58       info <general>: [plugin.video.mytube] <service.session.ytdlp> stopped
2025-04-03 19:03:28.507 T:58       info <general>: [plugin.video.mytube] <service.session> stopped
2025-04-03 19:03:28.507 T:58       info <general>: [plugin.video.mytube] <service> stopped
2025-04-03 19:03:28.712 T:60       info <general>: Twitch: Service: Shutdown
2025-04-03 19:03:29.624 T:62       info <general>: script.module.slyguy - Shared Service: Stopped
2025-04-03 19:03:29.654 T:63       info <general>: [service.manifests.mpd] <service.httpd> stopped
2025-04-03 19:03:29.654 T:63       info <general>: [service.manifests.mpd] <service> stopped
2025-04-03 19:03:29.662 T:64       info <general>: [service.upnext] UpNextMonitor -> Service stopped
2025-04-03 19:03:29.663 T:64      error <general>: EXCEPTION: No valid addon id could be obtained. None was passed and the script wasn't executed in a normal Kodi manner.
2025-04-03 19:03:29.665 T:7        info <general>: CServiceAddonManager: failed to stop service.xbmc.versioncheck (may have ended)
2025-04-03 19:03:29.665 T:66       info <general>: [service.yt-dlp] <service.mpd> stopped
2025-04-03 19:03:29.665 T:66       info <general>: [service.yt-dlp] <service> stopped
2025-04-03 19:03:29.754 T:7        info <general>: Application stopped
2025-04-03 19:03:29.954 T:7        info <general>: PVR Manager: Stopping
2025-04-03 19:03:30.150 T:77       info <general>: EPG Container: Persisting unsaved events...
2025-04-03 19:03:30.150 T:77       info <general>: EPG Container: Persisting events done
2025-04-03 19:03:30.151 T:74       info <general>: PVR Manager: Stopped
2025-04-03 19:03:30.204 T:7        info <general>: ADDON: Dll Destroyed - TVMosaic/DVBLink PVR Client
2025-04-03 19:03:30.628 T:7        info <general>: AddOnLog: peripheral.joystick: Disabling joystick interface "linux"
2025-04-03 19:03:30.628 T:7        info <general>: ADDON: Dll Destroyed - Joystick Support
2025-04-03 19:03:30.628 T:7        info <general>: ADDON: Dll Destroyed - X-Arcade Tankstick Driver
2025-04-03 19:03:30.628 T:7        info <general>: unload skin
2025-04-03 19:03:30.663 T:7        info <general>: Unloaded skin
2025-04-03 19:03:30.668 T:7        info <general>: unload sections
2025-04-03 19:03:30.671 T:7        info <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2025-04-03 19:03:30.673 T:7        info <general>: ADDON: Dll Destroyed - Archive support
2025-04-03 19:03:30.673 T:7        info <general>: ADDON: Dll Destroyed - RAR archive support
2025-04-03 19:03:30.674 T:7        info <general>: ADDON: Dll Destroyed - SFTP support
2025-04-03 19:03:30.709 T:7        info <general>: Exiting the application...
